name: PR Build and Check

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Maven Build
      run: mvn clean install

    # - name: Checkstyle Check
    #   run: mvn checkstyle:check

    # - name: JaCoCo Test Coverage
    #   run: mvn jacoco:check

    - name: Upload Reports
      uses: actions/upload-artifact@v2
      with:
        name: reports
        path: target/site/
